import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
//import ManualHeader from "../components/ManualHeader";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>彩票抽奖 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ManualHeader></ManualHeader> */}
      <Header></Header>
      <LotteryEntrance></LotteryEntrance>

      <main className={`${styles.main} ${inter.className}`}></main>
    </div>
  );
}
